sudo: false

language: node_js

node_js:
  - 7
  - 6
  - 5
  - 4

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - yarn install

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  - yarn coveralls
