sudo: false

git:
  depth: 10

branches:
  only:
    - master
    - next

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  include:
    - node_js: '10'
      script: yarn pretest
      env: JOB_PART=pretest
    - node_js: '10'
      script: yarn test-only:coverage
      env: JOB_PART=coverage
    - node_js: '8'
      script: yarn test-only
      env: JOB_PART=test-only 8
    - node_js: '6'
      script: yarn test-only
      env: JOB_PART=test-only 6

before_install:
  - nvm --version
  - node --version
  - npm --version
  - yarn --version

install:
  - yarn install

after_success:
  - if [ "$JOB_PART" = "coverage" ]; then cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi
