packages:
  - 'packages/**'
  - '!site/**'
autoInstallPeers: true
hoist: false
hoistWorkspacePackages: false

catalog:
  autoprefixer: ^10.6.1
  browserslist: ^4.29.3
  '@csstools/css-tokenizer': ^4.0.2
  postcss: ^8.5.28
  '@webref/css': 8.7.5
  mdn-data: 2.37.1
  '@colordx/core': ^7.2.0
  '@mdn/browser-compat-data': ^8.1.4

minimumReleaseAgeExclude:
  - postcss-calc

versioning:
  changelog:
    storage: repository
