packages:
  - 'packages/**'
  - '!site/**'
autoInstallPeers: true

catalog:
  browserslist: ^4.28.8
  postcss: ^8.5.26
  '@webref/css': 8.7.3
  mdn-data: 2.34.0

minimumReleaseAgeExclude:
  - postcss-calc@11.0.1

versioning:
  changelog:
    storage: repository
