packages:
  - 'packages/**'
  - '!site/**'
autoInstallPeers: true

catalog:
  autoprefixer: ^10.5.6
  browserslist: ^4.28.9
  '@csstools/css-tokenizer': ^4.0.0
  postcss: ^8.5.28
  '@webref/css': 8.7.4
  mdn-data: 2.35.0
  '@colordx/core': ^6.4.0

minimumReleaseAgeExclude:
  - postcss-calc

versioning:
  changelog:
    storage: repository
