name: Bug Report
description: Create a bug report to help us improve
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: Please make sure to provide the information we ask for. This will allow us to help you better.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: A bug happened! 'foo' should not be there.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected to see X or Y instead of 'foo'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please add link to a repo with a minimal reproduction. Or describe as detailed as possible how we can reproduce/verify the bug.
      placeholder: |
        Example steps (replace with your own):
        1. Clone my repo at https://github.com/<myuser>/example
        2. npm run minify
        3. You should see the error come up
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of cssnano you are using.
      placeholder: ex. v5.0.6
    validations:
      required: true
  - type: dropdown
    id: preset
    attributes:
      label: Preset
      description: Are you using one of the presets?
      options:
        - (no preset)
        - lite
        - default
        - advanced
    validations:
      required: true
  - type: textarea
    id: envinfo
    attributes:
      label: Environment
      description: |
        Please copy and paste the outout of running `npx envinfo --system`.
        This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        System:
          OS:
          CPU:
          Memory:
          Shell:
      render: shell
    validations:
      required: true
  - type: textarea
    id: nanoinfo
    attributes:
      label: Package details
      description: |
        Please copy and paste the outout of running `npm ls cssnano postcss`.
        This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        ├── cssnano@5.0.6
        └── postcss@8.3.5
      render: shell
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might be relevant
    validations:
      required: false
